version: '2'
volumes:
  www-volume:
    driver: local
services:
  php-fpm:
    build: .
    image: php-fpm
    env_file:
    - docker-config.env
    volumes:
    - www-volume:/var/www/html/
    - ./data:/var/www/html/data
  nginx:
    image: nginx:1.13.3-alpine
    command: nginx -g 'daemon off;' -c /var/www/html/docker-nginx.conf
    depends_on:
    - php-fpm
    ports:
    - "80:80"
    volumes_from:
    - php-fpm
