version: '2'
services:
  php-fpm:
    build: .
    image: php-fpm
    env_file:
    - docker-config.env
    volumes:
    - ./html/:/var/www/html/
  nginx:
    image: nginx:1.13.3-alpine
    command: nginx -g 'daemon off;' -c /var/www/src/docker-nginx.conf
    restart: always
    depends_on:
    - php-fpm
    ports:
    - "80:80"
    volumes_from:
    - php-fpm
